### ISSUE TITLE
[REQUEST] Add more phising Pages . 

### ISSUE THREAD

**Issue by isuruwa** [DarkSecDevelopers/LitePhish#17]
This is a nice project . But lack of phising pages . How I add more phising pages to this project

**Comment by prateek-chaubey** [comment]
If you want to add pages , you can read the instructions [here](https://github.com/DarkSecDevelopers/LitePhish/issues/8#issue-802696729) , and also a [sample page](https://github.com/DarkSecDevelopers/LitePhish/blob/70d34c4f5b9fe74f7fabb2d527f3fc7c7eb8dd2a/websites/sample.html#L1) is provided by @graysuit  for developers so that they can see how It works.
It will be useful for adding your own pages.
You can also join our [Discord Server](https://discord.gg/UGWC2BFEr5) , for further discussion.

**Comment by isuruwa** [comment]
Got it
