### ISSUE TITLE
Awesome Project

### ISSUE THREAD

**Issue by swagkarna** [DarkSecDevelopers/LitePhish#4]
Good Work Bro After you return to github. .All the best .keep contributing more  for educating kids like me  😜 😜 😜 😜

**Comment by graysuit** [comment]
Greetings @swagkarna ! 
Thank you so much brother for this motivation.
I didn't forget these great days, when we were noobs
And now we both are coders !
Lets keep going and make amazing contributions to internet.

**Comment by sTiKyt** [comment]
I'm sure @graysuit is happy to have feedback but please don't use issues for that matter @swagkarna , use discussions tab (Which i'll try and enable now)

**Comment by sTiKyt** [comment]
Nevermind, it's enabled already

**Comment by graysuit** [comment]
@sTiKyt 
He's my **old Indian friend** well in making phishing pages, that's why his feedback **worth**'s a lot.
Its good to see new **discussion** feature here. We can now give love, affection and feedback in **discussion**.
Anyway, I created an discord chat group,
I will be happy to have your **assistance**:
https://discord.gg/Hu5XPGMTuk
At there, we all are doing code development discussion including **usama**, me and **swagkarna**.
